version: '3.1'

services:
  fuseki:
    image: stain/jena-fuseki:3.14.0
    environment:
      - ADMIN_PASSWORD=admin
      - JVM_ARGS=-Xmx2g
    volumes:
      - ./data/fuseki:/fuseki
    ports:
      - 3030:3030
    restart: unless-stopped
