version: '3.1'

services:
  fuseki:
    image: stain/jena-fuseki:3.14.0
    environment:
      - ADMIN_PASSWORD=admin
      - JVM_ARGS=-Xmx2g
    volumes:
      - ./data/fuseki:/fuseki
    ports:
      - 3030:3030
    restart: unless-stopped

  api:
    image: bgs/strat
    build: .
    environment:
      - ENDPOINT=http://fuseki:3030/stratigraph/query
    ports:
      - 8000:80

