name: Run tests against Fuseki
on: push

jobs:
  db-test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: load data into Fuseki service
        run: |
          pip3 install requests SPARQLWrapper
          export FUSEKI_HOST=http://localhost:3030/
          python3 integration/fuseki_load.py

      - name: run the integration tests
        run: |
          pip3 install setuptools wheel gunicorn
          pip3 install -r requirements.txt
          pip3 install pytest
          export ENDPOINT=http://localhost:3030/stratigraph/query
          # Run the test server - better to rewrite the tests?
          export PYTHONPATH=.:..
          python3 -m pytest -vs integration

    # Service containers to run with `container-job`
    services:
      # Apache Jena Fuseki for external SPARQL endpoint
      fuseki:
        # Docker Hub image
        image: stain/jena-fuseki
        env:
          ADMIN_PASSWORD: admin
        ports:
          - 3030:3030
      # Stanford CoreNLP API for named entity recognition
      corenlp:
        image: docker.pkg.github.com/britishgeologicalsurvey/geo-ner-model/corenlp:v0.3
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 9000:9000
