name: Run tests
on: push

jobs:
  test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: run the unit tests
        run: |
          pip3 install setuptools>=42.0.0 wheel
          pip3 install -r requirements.txt
          pip3 install pytest flake8
          export PYTHONPATH=.:..
          python3 -m flake8 stratigraph tests scripts
          python3 -m pytest -vs tests
